[service]
Name="rhscm"
displayname="润合供应链订货系统"
version="v1.0"

host="test.dc.rpdns.com"
Port=7001

[Consul]
Host="10.1.1.239"
Port=8500

#[Mysql]
#Host="test.db.rpdns.com"
#Port=3306
#User="root"
#Pwd="Rp000000"
#Default="rhscm"

[Mysql]
Host="10.1.1.21"
Port=3306
User="root"
Pwd="123456"
Default="sharesping"

[MsSql]
Host="10.1.1.246"
Port=1433
User="sa"
Pwd="RPpet6306"
Default="rhgyl"

[Cache]
Host="10.1.1.120"
Port=6379
Pwd="123456"
Default=0

[Rsa]
PublicKey="rsa_1024_pub.pem"
PrivateKey="rsa_1024_priv.pem"
Issuer="rp-pet.com"